### ISSUE TITLE
Zoom funktioniert nicht

### ISSUE THREAD

**Issue by DanielKnerr** [hermlon/mandelbrot#1]
Hey, ich hab' dein Projekt gefunden. :)

Wenn ich auf einen Punkt klicke, würde ich erwarten, dass das Bild auf diesen Punkt zentriert wird. Stattdessen wird das Bild an eine fast willkürliche Stelle verschoben.

Ich glaub' das Problem kommt davon, dass die Berechnung des neuen Mittelpunkts (x und y) nicht die aktuellen Werte von x und y einbezieht:
https://github.com/hermlon/mandelbrot/blob/cd477f4a753ec3d74bf796f568529b2c8bb3cb03/mandelbrot.py#L51-L52

**Comment by hermlon** [comment]
Danke für den Hinweis, jetzt sollte es funktionieren!
